"""Gates for Phase-6 Task A1: the habit dial + the three contextual axes.

WHAT THIS FILE DEFENDS (PHASE6_PLAN Task A1, deliverable 4):
  (a) every Phase-5 personality gate still passes untouched -- enforced by
      `tests/test_personality.py` being unmodified, plus the explicit
      byte-identity pin below (`test_v1_sampler_is_untouched`);
  (b) style-invariance: one personality seed across all four dial settings has
      IDENTICAL non-predictability axes (only epsilon/temperature move);
  (c) the Phase-5 divergence floors (pair >=15%, vs-heuristic >=10%, measured
      argmax-style exactly as test_personality.py measures them) still hold at
      EVERY dial setting, H0 included;
  (d) behavioural pins for each new axis on hand-built states;
  (e) mirror sanity (4 copies bracket 6.5) at H0 and H2;
  (f) a measured mean per-decision choice entropy per setting, printed, and
      asserted strictly monotone H0 < H1 < H2 < H3.

MEASUREMENT NOTES (the honest caveats, stated up front)

* Divergence is measured with `greedy_choice`, which reads NEITHER epsilon nor
  temperature -- so per view the compared choices are IDENTICAL at all four
  settings by construction (`test_greedy_choice_is_identical_across_settings`
  pins exactly that).  The four reported numbers still differ slightly,
  because the state CORPUS is generated by a driver played at that setting and
  a habitual driver visits somewhat different positions.  So the four numbers
  are four samples of one quantity over four state distributions, not four
  independent effects of the dial -- read them that way.
  The gate has teeth regardless: the numbers are recomputed from the v2
  population, whose three NEW axes do change `_scores` and could have
  collapsed it toward itself or toward the heuristic.
* Entropy is computed in CLOSED FORM from the same mixture density the player
  actually samples from (eps/n + (1-eps)*softmax(scores/T)), over ONE fixed
  corpus of views shared by all four settings.  Sampling frequencies instead
  would add estimator noise, and letting each setting generate its own states
  would confound the dial with a shifted state distribution.
"""
import numpy as np
import pytest

from openhearts.engine import cards
from openhearts.engine.game import deal
from openhearts.engine.state import GameState
from openhearts.eval.harness import rotated_match
from openhearts.eval.stats import bootstrap_ci
from openhearts.players.heuristic import HeuristicPlayer
from openhearts.players.personality import (
    HABIT_SETTINGS,
    NEW_AXES_V2,
    PersonalityPlayer,
    make_population_v2,
    sample_personality,
    sample_personality_v2,
)

SETTINGS = ("H0", "H1", "H2", "H3")

DIVERGENCE_FLOOR = 0.15      # pre-registered, same as Phase 5
HEURISTIC_FLOOR = 0.10       # pre-registered, same as Phase 5


# ---------------------------------------------------------------- helpers

def _multi_legal_views(deal_seed, driver, limit=None):
    """Replay one deal with `driver` at all four seats; yield the views at
    every decision that had more than one legal card.  Verbatim from
    tests/test_personality.py so the two gates measure the same object."""
    state = deal(np.random.default_rng(deal_seed))
    out = []
    while not state.is_over():
        view = state.view_for(state.to_play)
        if bin(view.legal_moves).count("1") > 1:
            out.append(view)
        state.play(driver.choose(view))
    return out if limit is None else out[:limit]


def _disagreement(views, a, b):
    diff = sum(1 for v in views if a.greedy_choice(v) != b.greedy_choice(v))
    return diff / len(views)


class _HeuristicGreedy:
    def __init__(self):
        self.h = HeuristicPlayer()

    def greedy_choice(self, view):
        return self.h.choose(view)


_RANKS = "23456789TJQKA"
_SUITS = "cdsh"


def _c(name):
    """'Qc' -> card int.  Local so the pins read like a real hand."""
    return _SUITS.index(name[1]) * 13 + _RANKS.index(name[0])


def _m(names):
    m = 0
    for n in names:
        m |= cards.bit(_c(n))
    return m


def _state_from(hands, plays, to_play, trick_number=1, hearts_broken=False):
    """Build a concrete mid-trick state: `hands` are 4 card-name lists,
    `plays` is the card sequence already made starting at `to_play`."""
    st = GameState(hands=[_m(h) for h in hands])
    st.to_play = to_play
    st.trick_number = trick_number
    st.hearts_broken = hearts_broken
    for name in plays:
        st.play(_c(name))
    return st


# --------------------------------------------------- (a) v1 is untouched

def test_v1_sampler_is_untouched():
    """The Phase-5 draw is a frozen contract: v2's appended draws must not
    have perturbed a single v1 value, and the v1 sampler must leave the three
    new axes at exactly 0.0 (so v1 play is bitwise unchanged)."""
    for pid in range(1, 200):
        v1 = sample_personality(pid)
        v2 = sample_personality_v2(pid, "H2")
        for axis in NEW_AXES_V2:
            assert getattr(v1, axis) == 0.0
        for f in ("duck", "hoard", "q_posture", "q_strength", "lead_short",
                  "lead_long", "lead_heart", "heart_dump", "suit_quirk",
                  "danger"):
            assert getattr(v1, f) == getattr(v2, f)
        # H2 is the identity setting: the continuity anchor for Phase 5.
        assert v1.temperature == v2.temperature
        assert v1.epsilon == v2.epsilon


# ------------------------------------------- (b) style invariance of the dial

def test_dial_moves_only_predictability():
    style = [f for f in ("duck", "hoard", "q_posture", "q_strength",
                         "lead_short", "lead_long", "lead_heart",
                         "heart_dump", "suit_quirk", "danger") + NEW_AXES_V2]
    for pid in range(1, 120):
        ref = sample_personality_v2(pid, "H2")
        for h in SETTINGS:
            p = sample_personality_v2(pid, h)
            for f in style:
                assert getattr(p, f) == getattr(ref, f), (pid, h, f)


def test_dial_bands_are_respected_and_ordered():
    for pid in range(1, 300):
        prev_e = prev_t = -1.0
        for h in SETTINGS:
            p = sample_personality_v2(pid, h)
            lo_e, hi_e = HABIT_SETTINGS[h]["epsilon"]
            lo_t, hi_t = HABIT_SETTINGS[h]["temperature"]
            assert lo_e <= p.epsilon <= hi_e
            assert lo_t <= p.temperature <= hi_t
            # quantile-preserving => strictly increasing across settings
            assert p.epsilon > prev_e and p.temperature > prev_t
            prev_e, prev_t = p.epsilon, p.temperature
    assert HABIT_SETTINGS["H0"]["epsilon"][1] <= 0.02
    assert HABIT_SETTINGS["H0"]["epsilon"][0] >= 0.005


def test_greedy_choice_is_identical_across_settings():
    """The mechanical statement behind gate (c)'s identical numbers."""
    driver = PersonalityPlayer(np.random.default_rng(0),
                               sample_personality_v2(1, "H2"))
    views = _multi_legal_views(70000, driver)
    for pid in (6001, 6002, 6003):
        ref = PersonalityPlayer(np.random.default_rng(0),
                                sample_personality_v2(pid, "H2"))
        for h in SETTINGS:
            p = PersonalityPlayer(np.random.default_rng(0),
                                  sample_personality_v2(pid, h))
            assert all(p.greedy_choice(v) == ref.greedy_choice(v)
                       for v in views)


# ------------------------------------------------- (c) divergence at each dial

@pytest.mark.parametrize("habit", SETTINGS)
def test_divergence_between_personality_pairs_v2(habit):
    driver = PersonalityPlayer(np.random.default_rng(0),
                               sample_personality_v2(1, habit))
    rates = []
    for k in range(50):
        views = _multi_legal_views(70000 + k, driver)
        pa = PersonalityPlayer(np.random.default_rng(0),
                               sample_personality_v2(6000 + 2 * k, habit))
        pb = PersonalityPlayer(np.random.default_rng(0),
                               sample_personality_v2(6001 + 2 * k, habit))
        rates.append(_disagreement(views, pa, pb))
    mean = float(np.mean(rates))
    print(f"[divergence] {habit}: pair mean {mean:.3f}")
    assert mean >= DIVERGENCE_FLOOR, f"{habit} pair divergence {mean:.3f}"


@pytest.mark.parametrize("habit", SETTINGS)
def test_every_v2_personality_diverges_from_the_heuristic(habit):
    driver = PersonalityPlayer(np.random.default_rng(0),
                               sample_personality_v2(1, habit))
    views = []
    for k in range(6):
        views += _multi_legal_views(71000 + k, driver)
    href = _HeuristicGreedy()
    rates = [_disagreement(views,
                           PersonalityPlayer(np.random.default_rng(0),
                                             sample_personality_v2(6000 + k,
                                                                   habit)),
                           href)
             for k in range(50)]
    print(f"[divergence] {habit}: vs-heuristic mean {np.mean(rates):.3f} "
          f"min {min(rates):.3f}")
    assert min(rates) >= HEURISTIC_FLOOR, (
        f"{habit} min vs-heuristic divergence {min(rates):.3f}")


# ------------------------------- the new axes actually buy SPAN (deliverable 2)

# Pre-registered floor.  Not a strength claim -- just "the three appended axes
# are not decoration".  Set low because they fire only in their contexts (safe
# tricks, early leads/discards, a burdened trick-winner), which are a minority
# of decisions; anything above a few percent means real behavioural span.
NEW_AXIS_SPAN_FLOOR = 0.05


def test_new_axes_change_play_at_h2():
    """v2-H2 vs v1 at the SAME personality seed.

    H2 is the identity dial setting and the v1 draws are bit-identical, so the
    ONLY difference between the two players is the three appended axes.  The
    greedy disagreement between them is therefore exactly the size of the
    behavioural discontinuity A2 will see at H2 -- pre-registered here so the
    lead has it before the curve runs, per the plan's note that "a material
    deviation at H2 is itself a finding about the new axes".
    """
    driver = PersonalityPlayer(np.random.default_rng(0),
                               sample_personality_v2(1, "H2"))
    views = []
    for k in range(6):
        views += _multi_legal_views(71000 + k, driver)
    rates = []
    for k in range(50):
        pid = 6000 + k
        rates.append(_disagreement(
            views,
            PersonalityPlayer(np.random.default_rng(0),
                              sample_personality_v2(pid, "H2")),
            PersonalityPlayer(np.random.default_rng(0),
                              sample_personality(pid))))
    mean = float(np.mean(rates))
    print(f"[span] v2(H2) vs v1, same seed: mean {mean:.3f} "
          f"min {min(rates):.3f} max {max(rates):.3f}")
    assert mean >= NEW_AXIS_SPAN_FLOOR, f"new axes barely move play: {mean:.3f}"


# --------------------------------------------- (d) new-axis behavioural pins

def _forced(axis, value, **rest):
    """A personality with every axis neutral except the one under test, so a
    pin cannot be passed by some other axis's accident."""
    base = dict(duck=0.8, hoard=0.0, q_posture="avoid", q_strength=0.0,
                lead_short=0.0, lead_long=0.0, lead_heart=0.0, heart_dump=0.0,
                suit_quirk=(0.0, 0.0, 0.0, 0.0), danger=0.0, temperature=1.0,
                epsilon=0.0, safe_dump=0.0, void_engineer=0.0,
                feed_leader=0.0)
    base.update(rest)
    base[axis] = value
    from openhearts.players.personality import PersonalityParams
    return PersonalityPlayer(np.random.default_rng(0),
                             PersonalityParams(**base))


def test_pin_safe_dump_the_priya_move():
    """Priya's trick, verbatim from PHASE6_PLAN Ruling 1.

    Seat 3 is LAST to a club trick carrying no points and holding Q(clubs)
    and 8(clubs).  The 8 also beats the trick, so BOTH legal cards win it --
    the choice is purely 'which high card do I shed'.  High safe-dump plays
    the Qc (unload the dangerous card on a free trick); a duck-flavoured
    low safe-dump keeps it and plays the 8c.
    """
    hands = [["2c", "3c", "2d", "3d", "4d"],
             ["4c", "5c", "5d", "6d", "7d"],
             ["6c", "7c", "8d", "9d", "Td"],
             ["Qc", "8c", "Jd", "Qd", "Kd"]]
    st = _state_from(hands, ["2c", "4c", "6c"], to_play=0)
    view = st.view_for(3)
    assert sorted(cards.cards_in(view.legal_moves)) == sorted(
        [_c("8c"), _c("Qc")])
    hi = _forced("safe_dump", 2.5)
    lo = _forced("safe_dump", -1.0)
    assert hi.greedy_choice(view) == _c("Qc")
    assert lo.greedy_choice(view) == _c("8c")


def test_pin_void_engineering():
    """Leading, trick 0, holding a 2-card diamond suit and a 5-card club suit
    with matched ranks.  A void engineer leads the doubleton diamond (two more
    plays and the suit is gone -> discards become free); a void-averse
    personality leads its long suit instead."""
    hands = [["3d", "4d", "3c", "5c", "7c", "9c", "Jc"],
             ["2c", "4c", "6c", "8c", "Tc", "2d", "5d"],
             ["Qc", "Kc", "Ac", "6d", "7d", "8d", "9d"],
             ["2s", "3s", "4s", "5s", "2h", "3h", "4h"]]
    st = _state_from(hands, [], to_play=0, trick_number=1)
    view = st.view_for(0)
    hi = _forced("void_engineer", 2.0)
    lo = _forced("void_engineer", -2.0)
    assert cards.suit(hi.greedy_choice(view)) == cards.DIAMONDS
    assert cards.suit(lo.greedy_choice(view)) == cards.CLUBS


def test_pin_leader_feeding():
    """Void in the led suit, so this is a discard and the current trick winner
    is certain to take whatever lands.  That winner (seat 1) already carries
    a big score.  A leader-feeder discards a heart onto them; a personality
    with the opposite tendency sheds a safe diamond instead."""
    hands = [["2c", "3c", "4c"],
             ["Ac", "Kc", "Qc"],
             ["5c", "6c", "7c"],
             ["2d", "Kh", "3h"]]
    st = _state_from(hands, ["2c", "Ac", "5c"], to_play=0, trick_number=1,
                     hearts_broken=True)
    # Synthetic: 18 points on trick 1 is unreachable in a real game.  This is
    # a feature pin, not a game replay -- the score is set purely to drive
    # `_leader_burden` to its top of scale.
    st.scores = [0, 18, 1, 0]
    view = st.view_for(3)
    hi = _forced("feed_leader", 2.0)
    lo = _forced("feed_leader", -2.0)
    assert cards.suit(hi.greedy_choice(view)) == cards.HEARTS
    assert lo.greedy_choice(view) == _c("2d")


# ------------------------------------------------------- (e) mirror sanity

@pytest.mark.parametrize("habit", ["H0", "H2"])
@pytest.mark.parametrize("pid", [11, 12])
def test_mirror_average_is_six_point_five_v2(habit, pid):
    params = sample_personality_v2(pid, habit)
    counter = [0]

    def factory():
        counter[0] += 1
        return PersonalityPlayer(
            np.random.default_rng(900000 + 97 * pid + counter[0]), params)

    per_deal = rotated_match(range(100000, 100300), factory, factory)
    mean, lo, hi = bootstrap_ci(per_deal, rng=np.random.default_rng(7))
    print(f"[mirror] {habit} pid={pid}: {mean:.3f} ({lo:.2f}, {hi:.2f})")
    assert lo <= 6.5 <= hi, (
        f"{habit} mirror mean {mean:.3f} CI ({lo:.2f}, {hi:.2f})")


# --------------------------------------------------------- (f) entropy report

def _mean_entropy(views, params_by_pid):
    """Mean per-decision choice entropy (nats) of the ACTUAL mixture density
    eps/n + (1-eps)*softmax(scores/T), closed form."""
    tot, n = 0.0, 0
    for params in params_by_pid:
        pl = PersonalityPlayer(np.random.default_rng(0), params)
        for v in views:
            legal = cards.cards_in(v.legal_moves)
            k = len(legal)
            if k == 1:
                tot += 0.0
                n += 1
                continue
            s = pl._scores(v, legal)
            w = np.exp((s - s.max()) / params.temperature)
            p = params.epsilon / k + (1.0 - params.epsilon) * (w / w.sum())
            # 0*log0 == 0; the decomposition below drives probabilities to
            # exactly 0, which plain np.log turns into nan.
            tot += float(-np.sum(np.where(p > 0.0, p * np.log(np.where(
                p > 0.0, p, 1.0)), 0.0)))
            n += 1
    return tot / n


def test_entropy_is_monotone_across_the_dial():
    driver = PersonalityPlayer(np.random.default_rng(0),
                               sample_personality_v2(1, "H2"))
    views = []
    for k in range(8):
        views += _multi_legal_views(72000 + k, driver)
    pids = list(range(6100, 6140))
    report = {}
    for h in SETTINGS:
        report[h] = _mean_entropy(
            views, [sample_personality_v2(p, h) for p in pids])
    print("\n[entropy] mean per-decision choice entropy (nats), "
          f"{len(views)} views x {len(pids)} personalities")
    for h in SETTINGS:
        print(f"[entropy]   {h}: {report[h]:.4f}")
    vals = [report[h] for h in SETTINGS]
    assert vals[0] < vals[1] < vals[2] < vals[3], report

    # H0 DECOMPOSITION -- reported, not gated.  H0's residual entropy is NOT
    # all epsilon and temperature: identical scores among legal cards (two
    # equally-lowest clubs, several cards that beat the trick identically) are
    # a coin flip at ANY temperature.  That TIE FLOOR is what "near-
    # deterministic" actually means here, and A2's reading of an H0 null
    # depends on knowing its size -- an H0 null with a big tie floor is
    # ambiguous between "reading is dead" and "H0 was not habitual enough".
    # Flagged for the lead; deliberately NOT fixed inside A1 (out of scope).
    import dataclasses
    h0 = [sample_personality_v2(p, "H0") for p in pids]
    no_eps = _mean_entropy(
        views, [dataclasses.replace(p, epsilon=0.0) for p in h0])
    frozen = _mean_entropy(
        views, [dataclasses.replace(p, epsilon=0.0, temperature=0.01)
                for p in h0])
    print(f"[entropy]   H0 decomposition: as-drawn {report['H0']:.4f} | "
          f"epsilon=0 {no_eps:.4f} | epsilon=0,T=0.01 {frozen:.4f} (tie floor)")


# --------------------------------------------------------- populations

def test_make_population_v2_walls_and_shared_ids():
    a = make_population_v2()
    b = make_population_v2()
    assert a == b
    train, held = a
    assert set(train).isdisjoint(held)
    assert all(i > 0 for i in train + held)
    # the SAME ids at every setting -- H0-Priya and H2-Priya are one player
    from openhearts.players.personality import population_params_v2
    for h in SETTINGS:
        t, e = population_params_v2(h)
        assert list(t) == train and list(e) == held
        assert all(HABIT_SETTINGS[h]["epsilon"][0] <= p.epsilon
                   <= HABIT_SETTINGS[h]["epsilon"][1] for p in t.values())
    # and distinct from Phase 5's population seed range
    from openhearts.players.personality import make_population
    p5t, p5h = make_population(200, 50, 314159)
    assert not (set(train) & set(p5t + p5h))
