"""Gates for the Phase-5 personality population (PHASE5_PLAN Task 1).

Four pre-registered gates, verbatim from the plan:
  (a) legality fuzz over >=200 personalities, scores sum to 26;
  (b) determinism: same (rng seed, params) => identical history; different
      params => different play;
  (c) divergence: >=50 personality pairs on identical deals, mean per-decision
      disagreement >=15%; each personality vs plain HeuristicPlayer >=10%;
  (d) mirror sanity: 4 copies of one personality average 6.5.

MEASUREMENT METHOD for gate (c) -- documented per the plan's instruction to
"mind rng usage".  Two confounds have to be excluded:
  * comparing sampled choices couples the rng.  If both personalities are
    handed the same seeded stream, their epsilon rolls and softmax uniforms
    coincide, and on the epsilon branch they deviate to the SAME uniformly
    random card -- manufacturing agreement exactly where the population is
    most different.  Handing them independent streams does the opposite:
    a personality disagrees with ITSELF, so a homogeneous population would
    clear the floor and the gate would prove nothing.
  * so the load-bearing number is the GREEDY (argmax-of-score) choice, with
    epsilon and softmax sampling both switched off.  Self-disagreement is then
    exactly 0 and a collapsed population scores 0, so the floor has teeth.
    It is also the like-for-like comparison against HeuristicPlayer, which is
    deterministic.  Including noise only inflates the numbers.
States are generated by ONE fixed reference driver at all four seats and every
comparand is queried on the same view, so neither side's own play biases the
state distribution.  Caveat: states are driver-typical, which may under-sample
positions where personalities diverge most; the measured number is therefore
conservative in that direction.
"""
import numpy as np
import pytest

from openhearts.engine import cards
from openhearts.engine.game import deal, play_game
from openhearts.eval.harness import rotated_match
from openhearts.eval.stats import bootstrap_ci
from openhearts.players.heuristic import HeuristicPlayer
from openhearts.players.personality import (
    ANCHOR_IDS,
    PersonalityParams,
    PersonalityPlayer,
    make_population,
    sample_personality,
)


# ---------------------------------------------------------------- helpers

def _multi_legal_views(deal_seed, driver, limit=None):
    """Replay one deal with `driver` at all four seats; yield the views at
    every decision that had more than one legal card."""
    state = deal(np.random.default_rng(deal_seed))
    out = []
    while not state.is_over():
        view = state.view_for(state.to_play)
        if bin(view.legal_moves).count("1") > 1:
            out.append(view)
        state.play(driver.choose(view))
    return out if limit is None else out[:limit]


def _disagreement(views, a, b):
    """Fraction of views where two greedy choosers pick different cards."""
    diff = sum(1 for v in views if a.greedy_choice(v) != b.greedy_choice(v))
    return diff / len(views)


class _HeuristicGreedy:
    """Adapter so HeuristicPlayer can be used in the greedy comparison."""

    def __init__(self):
        self.h = HeuristicPlayer()

    def greedy_choice(self, view):
        return self.h.choose(view)


# ---------------------------------------------------------------- gate (a)

def test_legality_fuzz_200_personalities():
    ids = list(range(1000, 1200))
    assert len(ids) >= 200
    for i, pid in enumerate(ids):
        params = sample_personality(pid)
        players = [
            PersonalityPlayer(np.random.default_rng(pid * 4 + s), params)
            for s in range(4)
        ]
        state = play_game(deal(np.random.default_rng(50000 + i)), players)
        assert sum(state.scores) == 26
        assert all(s >= 0 for s in state.scores)


def test_legality_fuzz_mixed_tables():
    """Four DIFFERENT personalities at one table (the Task-2 seating shape)."""
    for i in range(60):
        players = [
            PersonalityPlayer(np.random.default_rng(9000 + 4 * i + s),
                              sample_personality(2000 + 4 * i + s))
            for s in range(4)
        ]
        state = play_game(deal(np.random.default_rng(60000 + i)), players)
        assert sum(state.scores) == 26


# ---------------------------------------------------------------- gate (b)

def test_determinism_same_seed_same_params():
    params = sample_personality(77)
    hist = []
    for _ in range(2):
        players = [
            PersonalityPlayer(np.random.default_rng(100 + s), params)
            for s in range(4)
        ]
        hist.append(play_game(deal(np.random.default_rng(11)), players).history)
    assert hist[0] == hist[1]


def test_determinism_different_params_different_play():
    """Same rng seeds, different params => the game diverges, for most pairs."""
    differing = 0
    trials = 20
    for k in range(trials):
        a, b = sample_personality(300 + 2 * k), sample_personality(301 + 2 * k)
        assert a != b
        games = []
        for params in (a, b):
            players = [
                PersonalityPlayer(np.random.default_rng(500 + s), params)
                for s in range(4)
            ]
            games.append(
                play_game(deal(np.random.default_rng(12 + k)), players).history)
        differing += (games[0] != games[1])
    assert differing == trials


# ---------------------------------------------------------------- gate (c)

DIVERGENCE_FLOOR = 0.15      # pre-registered: personality vs personality
HEURISTIC_FLOOR = 0.10       # pre-registered: personality vs plain heuristic


def test_divergence_between_personality_pairs():
    driver = PersonalityPlayer(np.random.default_rng(0), sample_personality(1))
    rates = []
    for k in range(50):
        views = _multi_legal_views(70000 + k, driver)
        pa = PersonalityPlayer(np.random.default_rng(0),
                               sample_personality(4000 + 2 * k))
        pb = PersonalityPlayer(np.random.default_rng(0),
                               sample_personality(4001 + 2 * k))
        rates.append(_disagreement(views, pa, pb))
    mean = float(np.mean(rates))
    assert mean >= DIVERGENCE_FLOOR, f"pair divergence {mean:.3f}"


def test_divergence_self_baseline_is_zero():
    """Sanity for the estimator: greedy choice disagrees with itself 0%."""
    driver = PersonalityPlayer(np.random.default_rng(0), sample_personality(1))
    views = _multi_legal_views(70000, driver)
    p = PersonalityPlayer(np.random.default_rng(0), sample_personality(4000))
    q = PersonalityPlayer(np.random.default_rng(1), sample_personality(4000))
    assert _disagreement(views, p, q) == 0.0


def test_every_personality_diverges_from_the_heuristic():
    driver = PersonalityPlayer(np.random.default_rng(0), sample_personality(1))
    views = []
    for k in range(6):
        views += _multi_legal_views(71000 + k, driver)
    href = _HeuristicGreedy()
    worst = 1.0
    for k in range(50):
        p = PersonalityPlayer(np.random.default_rng(0),
                              sample_personality(4000 + k))
        worst = min(worst, _disagreement(views, p, href))
    assert worst >= HEURISTIC_FLOOR, f"min vs-heuristic divergence {worst:.3f}"


# ---------------------------------------------------------------- gate (d)

@pytest.mark.parametrize("pid", [11, 12, 13])
def test_mirror_average_is_six_point_five(pid):
    """4 copies of one personality, independent rngs, rotated identical deals:
    by exchangeability the expectation is exactly 26/4."""
    params = sample_personality(pid)
    counter = [0]

    def factory():
        counter[0] += 1
        return PersonalityPlayer(
            np.random.default_rng(800000 + 97 * pid + counter[0]), params)

    # 300 deals x 4 rotations: the observed per-deal SD is ~2.9, so the 95%
    # half-width lands near 0.33 -- tight enough to catch a real symmetry
    # break, loose enough to be stable, and still ~1.5s for all three ids.
    per_deal = rotated_match(range(100000, 100300), factory, factory)
    mean, lo, hi = bootstrap_ci(per_deal, rng=np.random.default_rng(7))
    assert lo <= 6.5 <= hi, (
        f"mirror mean {mean:.3f} CI ({lo:.2f}, {hi:.2f}) excludes 6.5")


# ---------------------------------------------------------------- population

def test_make_population_splits_and_is_deterministic():
    a = make_population(200, 50, master_seed=5)
    b = make_population(200, 50, master_seed=5)
    assert a == b
    train, held = a
    assert len(train) == 200 and len(held) == 50
    assert set(train).isdisjoint(held)
    assert len(set(train)) == 200 and len(set(held)) == 50
    assert all(i > 0 for i in train + held)
    assert make_population(200, 50, master_seed=6) != a


def test_anchor_ids_are_negative_and_documented():
    assert set(ANCHOR_IDS.values()) == {-1, -2, -3}
    assert all(v < 0 for v in ANCHOR_IDS.values())
    train, held = make_population(20, 5, master_seed=1)
    assert not set(ANCHOR_IDS.values()) & set(train + held)


def test_params_are_a_frozen_documented_dataclass():
    p = sample_personality(1)
    assert isinstance(p, PersonalityParams)
    with pytest.raises(Exception):
        p.epsilon = 0.5
    for pid in range(1, 300):
        q = sample_personality(pid)
        assert 0.03 <= q.epsilon <= 0.25
        assert q.q_posture in ("hunt", "dump_early", "avoid")


def test_player_only_touches_the_view():
    """Cheap structural check: choose() accepts a PlayerView and nothing else."""
    state = deal(np.random.default_rng(3))
    p = PersonalityPlayer(np.random.default_rng(0), sample_personality(9))
    view = state.view_for(state.to_play)
    card = p.choose(view)
    assert view.legal_moves & cards.bit(card)
